// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/themes/BoldBlue.tsx": () => import("../components/mockups/themes/BoldBlue.tsx"),
  "./components/mockups/themes/DeepTeal.tsx": () => import("../components/mockups/themes/DeepTeal.tsx"),
  "./components/mockups/themes/MultiColor.tsx": () => import("../components/mockups/themes/MultiColor.tsx"),
  "./components/mockups/themes/PurpleGradient.tsx": () => import("../components/mockups/themes/PurpleGradient.tsx")
};
