import { DEMO_METRICS } from "@/lib/constants";
import { LineChart, Line, BarChart, Bar, PieChart, Pie, RadialBarChart, RadialBar, XAxis, YAxis, CartesianGrid, Tooltip as RechartsTooltip, Legend, ResponsiveContainer, Cell } from "recharts";

const COLORS = ['#3b82f6', '#06b6d4', '#f59e0b', '#10b981', '#8b5cf6'];

const appPointData = [
  { name: 'Jun', used: 1200, entitled: 2400 },
  { name: 'Jul', used: 1400, entitled: 2400 },
  { name: 'Aug', used: 1350, entitled: 2400 },
  { name: 'Sep', used: 1500, entitled: 2400 },
  { name: 'Oct', used: 1620, entitled: 2400 },
  { name: 'Nov', used: 1847, entitled: 2400 },
  { name: 'Dec', used: 1750, entitled: 2400 },
  { name: 'Jan', used: 1600, entitled: 2400 },
  { name: 'Feb', used: 1650, entitled: 2400 },
  { name: 'Mar', used: 1700, entitled: 2400 },
  { name: 'Apr', used: 1800, entitled: 2400 },
  { name: 'May', used: 1820, entitled: 2400 },
];

const roleData = [
  { name: 'Admin', value: 5 },
  { name: 'Delivery', value: 12 },
  { name: 'Asset Mgr', value: 18 },
  { name: 'Scheduler', value: 15 },
  { name: 'Field Tech', value: 31 },
  { name: 'Finance', value: 8 },
  { name: 'Auditor', value: 5 },
];

const assetClassData = [
  { name: 'Substations', value: 42 },
  { name: 'Transformers', value: 67 },
  { name: 'Transmission', value: 28 },
  { name: 'Smart Meters', value: 156 },
  { name: 'Control Sys', value: 19 },
  { name: 'Vehicles', value: 34 },
];

const impactData = [
  { name: 'Critical', value: 0, fill: '#ef4444' },
  { name: 'High', value: 2, fill: '#f97316' },
  { name: 'Medium', value: 3, fill: '#eab308' },
  { name: 'Low', value: 2, fill: '#3b82f6' },
];

export default function Media() {
  return (
    <div className="container mx-auto px-4 py-24 min-h-screen">
      <div className="text-center mb-20">
        <h1 className="text-5xl font-bold mb-6">Charts & Visual Outputs</h1>
        <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
          Interactive evidence generated by the MASReady engine using fictional MAS9 Power data.
        </p>
      </div>

      <div className="grid lg:grid-cols-2 gap-8 mb-24">
        {/* AppPoints Trend */}
        <div className="rounded-xl border border-white/10 bg-card p-6">
          <h3 className="text-lg font-semibold mb-6">License AppPoints Trend</h3>
          <div className="h-[300px]">
            <ResponsiveContainer width="100%" height="100%">
              <LineChart data={appPointData}>
                <CartesianGrid strokeDasharray="3 3" stroke="#ffffff10" />
                <XAxis dataKey="name" stroke="#888888" fontSize={12} tickLine={false} axisLine={false} />
                <YAxis stroke="#888888" fontSize={12} tickLine={false} axisLine={false} />
                <RechartsTooltip contentStyle={{ backgroundColor: '#0d1426', borderColor: '#ffffff20' }} />
                <Legend />
                <Line type="monotone" dataKey="used" stroke="#3b82f6" strokeWidth={3} dot={false} />
                <Line type="monotone" dataKey="entitled" stroke="#06b6d4" strokeWidth={3} strokeDasharray="5 5" dot={false} />
              </LineChart>
            </ResponsiveContainer>
          </div>
        </div>

        {/* User Roles */}
        <div className="rounded-xl border border-white/10 bg-card p-6">
          <h3 className="text-lg font-semibold mb-6">User Role Distribution</h3>
          <div className="h-[300px]">
            <ResponsiveContainer width="100%" height="100%">
              <PieChart>
                <Pie data={roleData} cx="50%" cy="50%" innerRadius={80} outerRadius={110} paddingAngle={5} dataKey="value">
                  {roleData.map((entry, index) => (
                    <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />
                  ))}
                </Pie>
                <RechartsTooltip contentStyle={{ backgroundColor: '#0d1426', borderColor: '#ffffff20' }} />
                <Legend />
              </PieChart>
            </ResponsiveContainer>
          </div>
        </div>

        {/* Asset Classes */}
        <div className="rounded-xl border border-white/10 bg-card p-6">
          <h3 className="text-lg font-semibold mb-6">Asset Class Distribution</h3>
          <div className="h-[300px]">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={assetClassData}>
                <CartesianGrid strokeDasharray="3 3" stroke="#ffffff10" vertical={false} />
                <XAxis dataKey="name" stroke="#888888" fontSize={12} tickLine={false} axisLine={false} />
                <YAxis stroke="#888888" fontSize={12} tickLine={false} axisLine={false} />
                <RechartsTooltip contentStyle={{ backgroundColor: '#0d1426', borderColor: '#ffffff20' }} cursor={{fill: '#ffffff05'}} />
                <Bar dataKey="value" fill="#06b6d4" radius={[4, 4, 0, 0]} />
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>

        {/* Patch Impact */}
        <div className="rounded-xl border border-white/10 bg-card p-6">
          <h3 className="text-lg font-semibold mb-6">Patch Impact Risk</h3>
          <div className="h-[300px]">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={impactData}>
                <CartesianGrid strokeDasharray="3 3" stroke="#ffffff10" vertical={false} />
                <XAxis dataKey="name" stroke="#888888" fontSize={12} tickLine={false} axisLine={false} />
                <YAxis stroke="#888888" fontSize={12} tickLine={false} axisLine={false} allowDecimals={false} />
                <RechartsTooltip contentStyle={{ backgroundColor: '#0d1426', borderColor: '#ffffff20' }} cursor={{fill: '#ffffff05'}} />
                <Bar dataKey="value" radius={[4, 4, 0, 0]}>
                  {impactData.map((entry, index) => (
                    <Cell key={`cell-${index}`} fill={entry.fill} />
                  ))}
                </Bar>
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>
      </div>
      
      <div className="rounded-xl border border-destructive/20 bg-destructive/5 p-6 text-center text-destructive max-w-2xl mx-auto">
        Playwright trace files are internal-only and are not published here.
      </div>
    </div>
  );
}
